### ISSUE TITLE
Removed from CRAN - Is this package going to be maintained?

### ISSUE THREAD

**Issue by serbinsh** [meireles/spectrolab#10]
Package ‘spectrolab’ was removed from the CRAN repository.
Formerly available versions can be obtained from the archive.
Archived on 2020-03-07 as check problems were not corrected despite reminders.
Please use the canonical form https://CRAN.R-project.org/package=spectrolab to link to this page.

I have found this package particularly useful for helping to process spectral data from SVC instruments but it looks like it is perhaps no longer being actively maintained?  Is that accurate?

**Comment by meireles** [comment]
@serbinsh Crap, I hadn't been notifications in my email until I updated it recently and I have been teaching like crazy until now, so I had no time to do software development.
We did quite a bit of refactoring and API changes that haven't been pushed here yet. I'll have time to work on this next week during spring break.

**Comment by serbinsh** [comment]
Great, thanks! No worries right now everything still working, I just wanted to check
