### ISSUE TITLE
read_spectra funciton not working properly

### ISSUE THREAD

**Issue by Bidhan-ghimire** [meireles/spectrolab#17]
I tried to read spectra from a folder containing .sed files and the reflectance value are not consistent among themselves or not always the same as the value in the .sed file. It looks like they are either multiplied by 100 or divided by 100. Please see attached pictures.[
<img width="127" alt="notepad" src="https://user-images.githubusercontent.com/61349582/195227354-d03a1e67-b77e-4ec8-9cb0-81503c89be6c.PNG">
<img width="519" alt="R" src="https://user-images.githubusercontent.com/61349582/195227357-66deb5ad-78c0-467d-b55b-2cab99f8a65b.PNG">
](url)

**Comment by Bidhan-ghimire** [comment]
The first picture is the value I see when I directly open the file using a notepad and the second picture is when I read the value using Spectrolab's read_spectra function.

**Comment by Bidhan-ghimire** [comment]
Please see the warning that is raised while using the read_spectra function.
![warnings](https://user-images.githubusercontent.com/61349582/195228075-686b7109-0fa5-4ed5-8df0-f261401b596b.png)

**Comment by meireles** [comment]
fixed in #72712a18e1697ba20b26386089f8debd53aa8632
